<?php if ( ! defined( 'ABSPATH' ) ) exit;

include_once('includes/RESA_Logger.php');
include_once('includes/RESA_Tools.php');
include_once('includes/RESA_Variables.php');
include_once('includes/RESA_EntityDTO.php');
include_once('includes/RESA_Controller.php');
include_once('includes/RESA_Exception.php');

include_once('includes/entities/RESA_InfoCalendar.php');
include_once('includes/entities/RESA_Alert.php');
include_once('includes/entities/RESA_LogNotification.php');
include_once('includes/entities/RESA_EmailCustomer.php');
include_once('includes/entities/RESA_AppointmentMember.php');
include_once('includes/entities/RESA_AppointmentNumberPrice.php');
include_once('includes/entities/RESA_AppointmentReduction.php');
include_once('includes/entities/RESA_Appointment.php');
include_once('includes/entities/RESA_Payment.php');
include_once('includes/entities/RESA_AskPayment.php');
include_once('includes/entities/RESA_Customer.php');
include_once('includes/entities/RESA_ServiceMemberPriority.php');
include_once('includes/entities/RESA_ServicePrice.php');
include_once('includes/entities/RESA_ServiceTimeslot.php');
include_once('includes/entities/RESA_ServiceAvailability.php');
include_once('includes/entities/RESA_ServiceConstraint.php');
include_once('includes/entities/RESA_Service.php');
include_once('includes/entities/RESA_MemberAvailabilityService.php');
include_once('includes/entities/RESA_MemberAvailability.php');
include_once('includes/entities/RESA_MemberLink.php');
include_once('includes/entities/RESA_MemberLinkService.php');
include_once('includes/entities/RESA_MemberConstraint.php');
include_once('includes/entities/RESA_Member.php');
include_once('includes/entities/RESA_Equipment.php');
include_once('includes/entities/RESA_StaticGroup.php');
include_once('includes/entities/RESA_Booking.php');
include_once('includes/entities/RESA_ReductionConditionApplication.php');
include_once('includes/entities/RESA_ReductionConditionsApplication.php');
include_once('includes/entities/RESA_ReductionApplication.php');
include_once('includes/entities/RESA_ReductionConditionService.php');
include_once('includes/entities/RESA_ReductionCondition.php');
include_once('includes/entities/RESA_ReductionConditions.php');
include_once('includes/entities/RESA_Reduction.php');
include_once('includes/entities/RESA_BookingReduction.php');
include_once('includes/entities/RESA_BookingCustomReduction.php');
include_once('includes/entities/RESA_Group.php');
include_once('includes/entities/RESA_Form.php');

include_once('includes/RESA_Crons.php');
include_once('includes/RESA_Algorithms.php');
include_once('includes/RESA_Mailer.php');
include_once('includes/RESA_GDPRManager.php');
include_once('includes/RESA_HooksManager.php');
include_once('includes/RESA_Session.php');
include_once('includes/RESA_UpdatesManager.php');
include_once('includes/RESA_InstallManager.php');
include_once('includes/RESA_ExportImport.php');
include_once('includes/RESA_Extension.php');
include_once('includes/wordpress-environment/W18T.class.php');
include_once('includes/RESA_StripeConnect.php');

include_once('includes/PhpImap/__autoload.php');
include_once('includes/RESA_ImapManager.php');

include_once('controller/RESA_ParentController.php');

include_once('controller/RESA_GlobalController.php');
include_once('controller/RESA_BackendController.php');
if(file_exists(__DIR__.'/controller/RESA_SystemInfoController.php')){
  include_once('controller/RESA_SystemInfoController.php');
}
include_once('controller/RESA_ParametersController.php');
include_once('controller/RESA_ReductionsController.php');
include_once('controller/RESA_AdminMainController.php');

include_once('controller/RESA_FormPublicController.php');
include_once('controller/RESA_AskAccountController.php');
include_once('controller/RESA_AccountController.php');
include_once('controller/RESA_PublicMainController.php');

//API
include_once('api/middleware.php');
include_once('api/activities/activities.routes.php');
include_once('api/activities/activities.controller.php');
include_once('api/activity/activity.routes.php');
include_once('api/activity/activity.controller.php');
include_once('api/algorithms/algorithms.routes.php');
include_once('api/algorithms/algorithms.controller.php');
include_once('api/forms/forms.routes.php');
include_once('api/forms/forms.controller.php');
include_once('api/bookings/bookings.routes.php');
include_once('api/bookings/bookings.controller.php');
include_once('api/members/members.routes.php');
include_once('api/members/members.controller.php');
include_once('api/equipments/equipments.routes.php');
include_once('api/equipments/equipments.controller.php');
include_once('api/reductions/reductions.routes.php');
include_once('api/reductions/reductions.controller.php');
include_once('api/groups/groups.routes.php');
include_once('api/groups/groups.controller.php');
include_once('api/installation/installation.routes.php');
include_once('api/installation/installation.controller.php');
include_once('api/notifications/notifications.routes.php');
include_once('api/notifications/notifications.controller.php');
include_once('api/settings/settings.routes.php');
include_once('api/settings/settings.controller.php');
include_once('api/calendars/calendars.routes.php');
include_once('api/calendars/calendars.controller.php');
include_once('api/calendarBackend/calendarBackend.routes.php');
include_once('api/calendarBackend/calendarBackend.controller.php');
include_once('api/user/user.routes.php');
include_once('api/user/user.controller.php');
include_once('api/customers/customers.routes.php');
include_once('api/customers/customers.controller.php');
include_once('api/planning/planning.routes.php');
include_once('api/planning/planning.controller.php');
include_once('api/statistics/statistics.routes.php');
include_once('api/statistics/statistics.controller.php');
include_once('api/logNotificationCenter/logNotificationCenter.routes.php');
include_once('api/logNotificationCenter/logNotificationCenter.controller.php');
